name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 登录 SWR
    - name: Login to SWR
      run: |
        echo "${{ secrets.SWR_PASSWORD }}" | docker login swr.cn-north-4.myhuaweicloud.com \
          -u ${{ secrets.SWR_USERNAME }} \
          --password-stdin

    # 构建镜像（强制写死路径，避免 secret 错）
    - name: Build image
      run: |
        docker build -t swr.cn-north-4.myhuaweicloud.com/stu2558/backend:${{ github.sha }} ./backend

    # 推送镜像
    - name: Push image
      run: |
        docker push swr.cn-north-4.myhuaweicloud.com/stu2558/backend:${{ github.sha }}

    # 部署 K8s
    - name: Deploy to Kubernetes
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

        kubectl set image deployment/backend \
          backend=swr.cn-north-4.myhuaweicloud.com/stu2558/backend:${{ github.sha }}
        kubectl rollout status deployment/backend
