apiVersion: v1
kind: Service
metadata:
   name: backend-svc
   annotations:
     kubernetes.io/elb.class: union
spec:
   type: LoadBalancer
   selector:
     app: backend
   ports:
   - port: 80
     targetPort: 5000
