kind: Config
apiVersion: v1
preferences: {}
clusters:
  - name: internalCluster
    cluster:
      server: https://192.168.0.12:5443
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJU…….YQ3FptLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  - name: externalCluster
    cluster:
      server: https://122.9.32.230:5443
      insecure-skip-tls-verify: true
  - name: externalClusterTLSVerify
    cluster:
      server: https://122.9.32.230:5443
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSU……….URS0tLS0tCg==
users:
  - name: user
    user:
      client-certificate-data: >-
        LS0tLS1CRUdJTiBDRVJUSU………USUZJQ0FURS0tLS0tCg==
      client-key-data: >-
        LS0tLS1……………….WFhLYXZTdGxtcUFUalFzeFhmbHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
contexts:
  - name: internal
    context:
      cluster: internalCluster
      user: user
  - name: external
    context:
      cluster: externalCluster
      user: user
  - name: externalTLSVerify
    context:
      cluster: externalClusterTLSVerify
      user: user
current-context: external
