apiVersion: v1 
data: 
.dockerconfigjson: eyJhdXRocyI6eyJzd3IuY24tbm9ydGgtNC5teWh1YXdlaWNsb3VkLmNvbSI6eyJ1c2VybmFtZSI6ImNuLW5vcnRoLTRASFNUM1c4SEE3TDBORFZINE5YSTYiLCJwYXNzd29yZCI6IjY0YzRjMDYxYWY3ZDgwOTBhZDM2YWZmYTBkYzhiODU0YmE1ODQ0NjQ3Yzg4OWI2MzgwNDUzM2M0N2UzNGM3MTgiLCJhdXRoIjoiWTI0dGJtOXlkR2d0TkVCSVUxUXpWemhJUVRkTU1FNUVWa2cwVGxoSk5qbzJOR00wWXpBMk1XRm1OMlE0TURrd1lXUXpObUZtWm1Fd1pHTTRZamcxTkdKaE5UZzBORFkwTjJNNE9EbGlOak00TURRMU16TmpORGRsTXpSak56RTQifX19 

kind: Secret 
metadata: 
name: swr-secret 

type: kubernetes.io/dockerconfigjson
