services:
  backend:
    build: ./backend
    ports: ["5000:5000"]
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
    depends_on: [redis]
    restart: always
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass 123456
    ports: ["6379:6379"]
    restart: always
  frontend:
    build: ./frontend
    ports: ["80:80"]
    depends_on: [backend]
    restart: always